name: Assign PR to creator

on:
  pull_request:
    types: [opened]

jobs:
  assign_creator:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-22.04
    env:
      HUSKY: 0
    steps:
      - name: Assign PR to creator
        uses: toshimaru/auto-author-assign@ebd30f10fb56e46eb0759a14951f36991426fed0 # v2.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
