on:
  pull_request:
    types: [opened, synchronize]

#changeset-release/main

env:
  BRANCH: ${{ vars.GITHUB_REF_NAME }}

jobs:
  release-rc:
    name: Release RC version to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4 # Use version from package.json
      - name: Setup Node.js 16 # It was default for Changesets action, check if it can be bumped to v18
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        name: Install pnpm
      - run: pnpm install
      - run: echo "${{vars.GITHUB_REF_NAME}}"